# paths
images_path: "/mnt/DATA_SSD/Sample_Dataset/stereo_camera/RCam"
folder_out: "/home/kai/Desktop/DailySource/M23_03/D2303_30/calib"
# consts
BOARD_R: 0.04231
BOARD_W: 8
BOARD_H: 5
IMAGE_W: 1280
IMAGE_H: 720
AREA_RATIO_MAX: 0.40
AREA_RATIO_MIN: 0.15
CHANGE_RATIO: 0.1
ROTATE_IMAGE: True
# parameter
calib_test_num: -1
calib_mse_err_th: 1
calib_max_err_th: 5
calib_model: 3
